server:
  port: 8081
  
spring: 
  application:
    name: product-service
  datasource:
    initialize: 'false'
    username: 'amigoscode'
    url: jdbc:postgresql://localhost:5432/product
    password: 'password'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: create-drop
      show-sql: 'true'